import monitor1 from "../../assets/productslide/123.jpg";
import monitor2 from "../../assets/productslide/456.jpg";
import monitor3 from "../../assets/productslide/789.jpg";
import monitor4 from "../../assets/Monitor/122.jpg";

const monitors = [
  {
    id: "monitor-1",
    brand: "ASUS",
    model: "ROG Swift PG259QN",
    size: "24.5 Inch",
    resolution: "1920 x 1080 (Full HD)",
    refreshRate: "360Hz",
    panel: "IPS",
    responseTime: "1ms",
    price: 125000,
    oldPrice: 145000,
    image:monitor1,
    isNew: true,
  },
  {
    id: "monitor-2",
    brand: "Acer",
    model: "Predator XB273U",
    size: "27 Inch",
    resolution: "2560 x 1440 (QHD)",
    refreshRate: "240Hz",
    panel: "IPS",
    responseTime: "1ms",
    price: 98000,
    oldPrice: 115000,
    image: monitor2,
    isNew: true,
  },
  {
    id: "monitor-3",
    brand: "MSI",
    model: "Optix MAG274QRF-QD",
    size: "27 Inch",
    resolution: "2560 x 1440 (QHD)",
    refreshRate: "165Hz",
    panel: "Rapid IPS",
    responseTime: "1ms",
    price: 85000,
    oldPrice: 99000,
    image: monitor3,
    isNew: false,
  },
  {
    id: "monitor-4",
    brand: "Samsung",
    model: "Odyssey G7",
    size: "32 Inch Curved",
    resolution: "2560 x 1440 (QHD)",
    refreshRate: "240Hz",
    panel: "VA",
    responseTime: "1ms",
    price: 110000,
    oldPrice: 130000,
    image: monitor4,
    isNew: false,
  },
  // {
  //   id: 5,
  //   brand: "LG",
  //   model: "UltraGear 27GP850",
  //   size: "27 Inch",
  //   resolution: "2560 x 1440 (QHD)",
  //   refreshRate: "165Hz",
  //   panel: "Nano IPS",
  //   responseTime: "1ms",
  //   price: 92000,
  //   oldPrice: 108000,
  //   image: "",
  //   isNew: true,
  // },
  // {
  //   id: 6,
  //   brand: "Gigabyte",
  //   model: "AORUS FI27Q",
  //   size: "27 Inch",
  //   resolution: "2560 x 1440 (QHD)",
  //   refreshRate: "165Hz",
  //   panel: "IPS",
  //   responseTime: "1ms",
  //   price: 88000,
  //   oldPrice: 102000,
  //   image: "",
  //   isNew: false,
  // },
];

export default monitors;
